### ISSUE TITLE
🚀 Production Checklist

### ISSUE THREAD

**Issue by aradmargalit** [aradmargalit/milameter#30]
## Code 👨‍💻 
- [x] `TEST_OFFSET` is removed from the codebase (I'm fine keeping it at 0)
- [x] Configurations are updated to be dynamic based on environment (e.g. different local tokens)

## Integrations 🔗 
- [x] Dev Strava account and API application is created
- [ ] ~Dev Mapbox token is rotated and moved to `.env.local` to keep it out of the codebase (but public to the client)~
- [x] Prod Mapbox token is created, and restricted to our domain only

## Infra 🚀 
- [x] Domain is purchased
- [x] App is deployed (probably on [Vercel](https://vercel.com/))
- [x] HTTPS is configured

## Operations (optional) 👀 
- [x] Configure [Sentry](https://sentry.io/pricing/) to report on uncaught errors
